### ISSUE TITLE
Life table

### ISSUE THREAD

**Issue by earthcat12** [amvillegas/StMoMo#14]
I have mortality data from HMD and I used StMoMo package for the fitting and forecasting. One of the models I use is the Renshaw-Haberman. My code is:
```
ages.fit<-55:89
wxt<- genWeightMat(ages = 55:89, years = grstomo.male$years, clip = 3)
rh<-rh(link = "log", cohortAgeFun = "1")
rhfit.male<- fit(rh, data = grstomo.male, ages.fit = ages.fit, wxt=wxt)
```
Do you know how i can create a life table from this model?

Thank you

**Comment by amvillegas** [comment]
You should be able to get the rates, $\mu_{xt}$ using `fitted(rhfit.male, type = "rates")`. You can then these fitted rates to create a life table, e.g., using the `lifecontingencies` package
