### ISSUE TITLE
Suppress messages related to the fit() function

### ISSUE THREAD

**Issue by mpascariu** [amvillegas/StMoMo#15]
Hi Andreas,

Is there a way to suppress the messages printed during the fitting of a model?

Example:
```R
> M3  <- fit(lc(), Dxt = Dx, Ext = Ex, ages = x, 
+            years = y, ages.fit = x, wxt = wxt)

StMoMo: The following cohorts have been zero weigthed: 1850 1851 1852 2014 2015 2016 
StMoMo: Start fitting with gnm
Initialising
Running start-up iterations..
Running main iterations...........................................
Done
StMoMo: Finish fitting with gnm
```

`suppressMessages()` does not work because you are using `cat()` in your code to display messages.

Thanks!
Marius

**Comment by amvillegas** [comment]
Yes, you can suppress messages with argument `verbose = FALSE` in function fit. So this should work

`M3  <- fit(lc(), Dxt = Dx, Ext = Ex, ages = x, years = y, ages.fit = x, wxt = wxt, verbose = FALSE)`

**Comment by mpascariu** [comment]
Great. Thanks.
